name: Production - Terraform Plan
on:
  pull_request:
    branches:
      - main
    paths:
      - "prod/**"

permissions:
  id-token: write # This is required for requesting the JWT (OIDC)
  contents: read
  pull-requests: write

jobs:
  prod_terraform_plan:
    environment:
      name: Production
    env:
      tf_dir: "prod"

    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ env.tf_dir }}

    if: github.event.pull_request.state != 'approved'
    steps:
      - id: checkout_latest
        name: Checkout latest
        uses: actions/checkout@v4

      - id: tf_prep
        name: Terraform setup using oidc role
        uses: Innovate-Future-Foundation/common-action/setup-tf-aws@main
        with:
          terraform_dir: ${{ env.tf_dir }}
          terraform_version: ${{ vars.TF_VERSION }}
          backend_region: ${{ secrets.TF_BACKEND_REGION }}
          backend_role_arn: "arn:aws:iam::${{ secrets.AWS_PROD_ACCOUNT }}:role/oidc-${{ vars.REPO_ORG_ABBR }}-${{ github.event.repository.name }}"
          backend_state_bucket: ${{ secrets.TF_BACKEND_STATE_BUCKET }}
          backend_lockid_table: ${{ secrets.TF_BACKEND_LOCKID_TABLE }}

      - id: tf_plan
        name: Terraform Plan
        run: terraform plan -out .planfile
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_ecr_region: ${{ secrets.AWS_CENTRAL_ECR_REGION }}
          TF_VAR_repo_abbr: ${{ vars.REPO_ORG_ABBR }}
          TF_VAR_backend_repo: ${{ vars.REPO_BACKEND }}
          TF_VAR_dev_account_id: ${{ secrets.AWS_DEV_ACCOUNT }} 
          TF_VAR_uat_account_id: ${{ secrets.AWS_UAT_ACCOUNT }}
          TF_VAR_prod_account_id: ${{ secrets.AWS_PROD_ACCOUNT }}

      - id: publish_tf_plan
        name: Publish Plan to PR and S3
        uses: Innovate-Future-Foundation/common-action/publish-tfplan-s3@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tf_dir: ${{ env.tf_dir }}
          s3_bucket: ${{ secrets.WORKFLOW_TEMP_BUCKET }}
          obj_key: plans/plan-${{ github.event.pull_request.number }}_${{ env.tf_dir }}
